### PR TITLE
Package bumped & ul li style fix

### PR DESCRIPTION
**Pull request by PEM--**
The `ul li` style was set to `none` leading to list without bullets.

### CODE REVIEW

**Comment by PEM--** [comment]
@nicolaslopezj Any update on integrating this PR?

**Comment by nicolaslopezj** [comment]
Sorry for the delay

**Comment by PEM--** [comment]
No pb, my friend. We all have customers. By the way, my first OrionJS project is in production. My customer was really satisfied with it. Thanks for all the help that you've provided me.

**Comment by nicolaslopezj** [comment]
Thats great new @PEM--, thank for contributing so much in this project!

**Pull request merged**
